name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Install node modules
        run: |
          npm install
      - name: Run CI with Lefthook
        run: |
          yarn lefthook run ci-hook
      - name: Run test
        run: |
          npm run test